# Window border colors
# class                 border  backgr. text    indicator
client.focused          {color3} {color3} {color15} {color6}
client.focused_inactive {color8} {color0} {color8} {color0}
client.unfocused        {color8} {color0} {color8} {color0}
client.urgent           {color1} {color1} {color15} {color1}
client.placeholder      {color8} {color0} {color8} {color0}

