
#dolphin relared config
exec --no-startup-id export XDG_CURRENT_DESKTOP=KDE


# Setting multiple i3 layouts
exec --no-startup-id  "setxkbmap -layout us,ru -option 'grp:alt_shift_toggle'"

# Start XDG autostart .desktop files using dex. See also
# https://wiki.archlinux.org/index.php/XDG_Autostart

exec --no-startup-id dex --autostart --environment i3
exec --no-startup-id picom 
exec --no-startup-id wal -R


# The combination of xss-lock, nm-applet and pactl is a popular choice, so
# they are included here as an example. Modify as you see fit.

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork

# NetworkManager is the most popular way to manage wireless networks on Linux,
exec --no-startup-id nm-applet



exec --no-startup-id polybar
exec --no-startup-id pipewire
exec --no-startup-id pipewire-pulse
exec --no-startup-id wireplumber
exec --no-startup-id xcape -e 'Super_L=Alt_L|F1'
exec --no-startup-id xcape -e 'Super_L=Alt_L|F1'
