# removing ugly ass titles from i3
for_window [class="^.*"] border pixel 1

#adding floating to file chooser

for_window [class="Quickshell"] floating enable
for_window [title="Choose the wallpaper"] floating enable 
